                        <?= $this->extend('layouts/main') ?>
                        <?= $this->section('content') ?>
                            <div class="container-xxl flex-grow-1 container-p-y">
                              <div class="card app-calendar-wrapper">
                                <div class="row g-0">
                                  <!-- Calendar Sidebar -->
                                  <div class="col app-calendar-sidebar" id="app-calendar-sidebar">
                                    <div class="p-3">
                                      <!-- inline calendar (flatpicker) -->
                                      <div class="inline-calendar"></div>

                                      <hr class="container-m-nx mb-4 mt-3" />

                                      <!-- Filter -->
                                      <div class="mb-3 ms-3">
                                        <small class="text-small text-muted text-uppercase align-middle">Filter</small>
                                      </div>

                                      <div class="form-check mb-2 ms-3">
                                        <input
                                          class="form-check-input select-all"
                                          type="checkbox"
                                          id="selectAll"
                                          data-value="all"
                                          checked />
                                        <label class="form-check-label" for="selectAll">View All</label>
                                      </div>

                                      <div class="app-calendar-events-filter ms-3" id="jobFilterContainer">
                                          <!-- GENERATED BY JS -->
                                      </div>

                                    </div>
                                  </div>
                                  <!-- /Calendar Sidebar -->

                                  <!-- Calendar & Modal -->
                                  <div class="col app-calendar-content">
                                    <div class="card shadow-none border-0">
                                      <div class="card-body pb-0">
                                        <!-- FullCalendar -->
                                        <div id="calendar"></div>
                                      </div>
                                    </div>
                                    <div class="app-overlay"></div>
                                    <!-- FullCalendar Offcanvas -->
                                    <div
                                      class="offcanvas offcanvas-end event-sidebar"
                                      tabindex="-1"
                                      id="addEventSidebar"
                                      aria-labelledby="addEventSidebarLabel">
                                      <div class="offcanvas-header my-1">
                                        <h5 class="offcanvas-title" id="addEventSidebarLabel">
                                          Job Attendance Detail
                                        </h5>

                                        <button
                                          type="button"
                                          class="btn-close text-reset"
                                          data-bs-dismiss="offcanvas"
                                          aria-label="Close"></button>
                                      </div>
                                      <div class="offcanvas-body pt-0">

                                          <!-- JOB INFO -->
                                          <div class="mb-4">
                                            <h6 class="text-uppercase text-muted mb-2">Job Information</h6>

                                            <div class="mb-2">
                                              <small class="text-muted">Position</small>
                                              <div class="fw-semibold" id="job_position">-</div>
                                            </div>

                                            <div class="mb-2">
                                              <small class="text-muted">Category</small>
                                              <div id="job_category">-</div>
                                            </div>

                                            <div class="mb-2">
                                              <small class="text-muted">Date</small>
                                              <div id="job_date">-</div>
                                            </div>

                                            <div class="mb-2">
                                              <small class="text-muted">Time</small>
                                              <div id="job_time">-</div>
                                            </div>

                                            <div class="mb-2">
                                              <small class="text-muted">Fee</small>
                                              <div id="job_fee">-</div>
                                            </div>

                                            <div class="mb-2">
                                              <small class="text-muted">Location</small>
                                              <div id="job_location">-</div>
                                            </div>

                                            <div class="mb-2">
                                              <small class="text-muted">Status</small>
                                              <span class="badge bg-success" id="job_status">-</span>
                                            </div>
                                          </div>

                                          <hr>

                                          <!-- ATTENDANCE -->
                                            <div>
                                              <h6 class="text-uppercase text-muted mb-3">Attendance Records</h6>

                                              <div id="attendanceContainer">
                                                <div class="text-muted">No attendance data</div>
                                              </div>
                                            </div>


                                      </div>

                                    </div>
                                  </div>
                                  <!-- /Calendar & Modal -->
                                </div>
                              </div>
                            </div>
                        <?= $this->endSection() ?>
                        
                        <?= $this->section('scripts') ?>

                        <link rel="stylesheet" href="<?= base_url('assets/vendor/libs/node-waves/node-waves.css') ?>" />
                        <link rel="stylesheet" href="<?= base_url('assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css') ?>" />
                        <link rel="stylesheet" href="<?= base_url('assets/vendor/libs/typeahead-js/typeahead.css') ?>" />
                        <link rel="stylesheet" href="<?= base_url('assets/vendor/libs/fullcalendar/fullcalendar.css') ?>" />
                        <link rel="stylesheet" href="<?= base_url('assets/vendor/libs/flatpickr/flatpickr.css') ?>" />
                        <link rel="stylesheet" href="<?= base_url('assets/vendor/libs/select2/select2.css') ?>" />
                        <link rel="stylesheet" href="<?= base_url('assets/vendor/libs/quill/editor.css') ?>" />
                        <link rel="stylesheet" href="<?= base_url('assets/vendor/libs/@form-validation/form-validation.css') ?>" />
                        <link rel="stylesheet" href="<?= base_url('assets/vendor/css/pages/app-calendar.css') ?>" />

                        <!-- Vendors JS (WAJIB URUT) -->
                        <script src="<?= base_url('assets/vendor/libs/fullcalendar/fullcalendar.js') ?>"></script>
                        <script src="<?= base_url('assets/vendor/libs/moment/moment.js') ?>"></script>
                        <script src="<?= base_url('assets/vendor/libs/flatpickr/flatpickr.js') ?>"></script>
                        <script src="<?= base_url('assets/vendor/libs/select2/select2.js') ?>"></script>
                        <script src="<?= base_url('assets/vendor/libs/@form-validation/popular.js') ?>"></script>
                        <script src="<?= base_url('assets/vendor/libs/@form-validation/bootstrap5.js') ?>"></script>
                        <script src="<?= base_url('assets/vendor/libs/@form-validation/auto-focus.js') ?>"></script>

                        <!-- Main JS (HANYA SEKALI, PASTIKAN TIDAK DOUBLE DI LAYOUT) -->
                        <script src="<?= base_url('assets/js/main.js') ?>"></script>

                        <!-- Dummy Events (template) -->
                        <script src="<?= base_url('assets/js/app-calendar-events.js') ?>"></script>

                        <script>
                          window.TEMPLATE_COLORS = [
                            'primary',
                            'success',
                            'danger',
                            'warning',
                            'info',
                            'dark'
                          ];
                        </script>

                        <script>
                          window.events = [];
                          window.calendarsColor = {};

                          fetch('<?= base_url('admin/hotels/calendar') ?>')
                            .then(res => res.json())
                            .then(data => {

                              // ============================
                              // 1. Isi events
                              // ============================
                              window.events.splice(0, window.events.length, ...data);

                              // ============================
                              // 2. Posisi unik
                              // ============================
                              const positions = [...new Set(
                                data.map(ev => ev.extendedProps.calendar)
                              )];

                              // ============================
                              // 3. Warna dinamis
                              // ============================
                              const COLORS = ['primary', 'success', 'danger', 'warning', 'info', 'dark'];
                              positions.forEach((position, index) => {
                                window.calendarsColor[position] = COLORS[index % COLORS.length];
                              });

                              // ============================
                              // 4. Generate filter
                              // ============================
                              const container = document.getElementById('jobFilterContainer');
                              container.innerHTML = '';

                              positions.forEach(position => {
                                const value = position.toLowerCase();
                                const id = 'filter-' + value.replace(/\s+/g, '-');
                                const color = window.calendarsColor[position];

                                container.insertAdjacentHTML('beforeend', `
                                  <div class="form-check mb-2">
                                    <input
                                      class="form-check-input input-filter"
                                      type="checkbox"
                                      id="${id}"
                                      data-value="${value}"
                                      checked
                                    />
                                    <label class="form-check-label d-flex align-items-center gap-2" for="${id}">
                                      <span class="badge badge-dot bg-${color}"></span>
                                      ${position}
                                    </label>
                                  </div>
                                `);
                              });

                              // ============================
                              // 🔥 5. LISTENER FILTER REALTIME
                              // ============================
                              document.querySelectorAll('.input-filter').forEach(el => {
                                el.addEventListener('change', () => {
                                  if (window.calendar) {
                                    window.calendar.refetchEvents();
                                  }
                                });
                              });

                              // render pertama
                              if (window.calendar) {
                                window.calendar.refetchEvents();
                              }
                            })
                            .catch(err => {
                              console.error('Failed load job calendar', err);
                            });
                        </script>

                        <!-- App Calendar Logic (template) -->
                        <script src="<?= base_url('assets/js/app-calendar.js') ?>"></script>

                        <script>
                          /**
                           * ============================
                           * READONLY EVENT CLICK HANDLER
                           * ============================
                           */
                          document.addEventListener('DOMContentLoaded', function () {

                            // tunggu sampai calendar benar-benar ada
                            const waitCalendar = setInterval(() => {
                              if (!window.calendar) return;

                              clearInterval(waitCalendar);

                              // override eventClick TANPA MERUSAK FILTER
                              window.calendar.setOption('eventClick', function (info) {

                                const event = info.event;
                                const jobId = event.extendedProps.job_id;

                                // ======================
                                // JOB INFO (READONLY)
                                // ======================
                                document.getElementById('job_position').innerText =
                                  event.title ?? '-';

                                document.getElementById('job_category').innerText =
                                  event.extendedProps.category ?? '-';

                                document.getElementById('job_date').innerText =
                                  event.start.toLocaleDateString('id-ID') +
                                  ' - ' +
                                  event.end.toLocaleDateString('id-ID');

                                document.getElementById('job_time').innerText =
                                  event.start.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }) +
                                  ' - ' +
                                  event.end.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' });

                                document.getElementById('job_fee').innerText =
                                  'Rp ' + Number(event.extendedProps.fee).toLocaleString('id-ID');

                                document.getElementById('job_location').innerText =
                                  event.extendedProps.location ?? '-';

                                const statusBadge = document.getElementById('job_status');
                                statusBadge.innerText = event.extendedProps.status ?? '-';
                                statusBadge.className =
                                  'badge ' + (event.extendedProps.status === 'open'
                                    ? 'bg-success'
                                    : 'bg-secondary');

                                // ======================
                                // LOAD ATTENDANCE (API)
                                // ======================
                                const container = document.getElementById('attendanceContainer');
                                container.innerHTML =
                                  '<div class="text-muted">Loading attendance...</div>';

                                fetch(`<?= base_url('admin/hotels/calendar-attendance') ?>/${jobId}`)
                                  .then(res => res.json())
                                  .then(rows => {

                                      if (!rows || !rows.length) {
                                        container.innerHTML =
                                          '<div class="text-muted">No attendance record</div>';
                                        return;
                                      }

                                      let html = '<ul class="list-group list-group-flush">';

                                      rows.forEach(row => {

                                        const mapUrl = row.latitude && row.longitude
                                          ? `https://www.google.com/maps?q=${row.latitude},${row.longitude}`
                                          : null;

                                        const photoUrl = row.photo_path
                                          ? `<?= base_url() ?>/${row.photo_path}`
                                          : null;

                                        html += `
                                          <li class="list-group-item">
                                            <div class="d-flex justify-content-between align-items-center">
                                              <div>
                                                <span class="badge bg-primary text-uppercase">
                                                  ${row.type}
                                                </span>
                                                <div class="small text-muted mt-1">
                                                  ${new Date(row.created_at).toLocaleString('id-ID')}
                                                </div>
                                              </div>
                                            </div>

                                            ${mapUrl ? `
                                              <div class="mt-2">
                                                <a href="${mapUrl}" target="_blank" class="small text-primary">
                                                  📍 View Location
                                                </a>
                                              </div>
                                            ` : ''}

                                            ${photoUrl ? `
                                              <div class="mt-2">
                                                <img src="${photoUrl}" class="img-fluid rounded" style="max-height:120px">
                                              </div>
                                            ` : ''}

                                            ${row.device_info ? `
                                              <div class="mt-2 small text-muted">
                                                🖥 ${row.device_info}
                                              </div>
                                            ` : ''}
                                          </li>
                                        `;
                                      });

                                      html += '</ul>';
                                      container.innerHTML = html;
                                    })

                                  .catch(() => {
                                    container.innerHTML =
                                      '<div class="text-danger">Failed load attendance</div>';
                                  });

                                // ======================
                                // SHOW OFFCANVAS
                                // ======================
                                const offcanvasEl =
                                  document.getElementById('addEventSidebar');

                                const offcanvas =
                                  bootstrap.Offcanvas.getOrCreateInstance(offcanvasEl);

                                offcanvas.show();
                              });
                            }, 100);
                          });
                        </script>

                        <?= $this->endSection() ?>
